name: Update key

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"
permissions:
  contents: write
jobs:
  update_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run script to update key.txt
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node update_key.js

      - name: Commit and push updated key.txt
        uses: EndBug/add-and-commit@v9
        with:
          add: "key.txt"
          message: "Automated update of key"
          default_author: "github_actions"
